# Generated by Django 3.1.2 on 2020-10-24 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('linkphoto', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('date', models.DateField(null=True)),
                ('summary', models.TextField(null=True)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.voyage')),
            ],
        ),
        migrations.CreateModel(
            name='Linkstep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkrestaurant', models.URLField()),
                ('title_step', models.CharField(max_length=200, null=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.step')),
            ],
        ),
    ]
