# Generated by Django 3.1.2 on 2020-10-23 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voyagestep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('resume', models.CharField(max_length=800)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.voyage')),
            ],
        ),
        migrations.CreateModel(
            name='Linkstep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkrestaurant', models.URLField()),
                ('linkphoto', models.URLField()),
                ('voyagestep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.voyagestep')),
            ],
        ),
    ]
